language: generic
sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t pash04/simple-web-app:$SHA -t pash04/simple-web-app:latest .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pash04/simple-web-app:$SHA
  - docker push pash04/simple-web-app:latest

#deploy:
#  provider: elasticbeanstalk
#  region: "ap-south-1"
#  app: "simple-web-app"
#  env: "Simplewebapp-env"
#  bucket_name: "elasticbeanstalk-ap-south-1-462623432869"
#  bucket_path: "simple-web-app"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
